services:
  - type: web
    name: lol-support-agent-backend
    env: docker
    plan: free
    repo: https://github.com/Soulsto/support_ai_agent.git
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 8001